//
//  Constants.h
//  BreakoutGame-TX
//
//  Created by Tianxiang Dai on 2/4/18.
//  Copyright © 2018 Tianxiang Dai. All rights reserved.
//

#ifndef Constants_h
#define Constants_h

#define CURRENT_LANGUAGE 1
#define LANGUAGE_ENGLISH 1
#define LANGUAGE_CHINESE 2
#define IS_ALIVE true
#define IS_DEAD false
#define BALL_RADIUS 10.0f
#define BALL_INITIAL_POSITION_X 640.0f
#define BALL_INITIAL_POSITION_Y 640.0f
#define BALL_INITIAL_VELOCITY_X 10.0f
#define BALL_INITIAL_VELOCITY_Y -12.0f
#define BALL_VELOCITY_FACTOR sqrt(224.0f)
#define BALL_BOUNDING_BOX_X 10.0f
#define BALL_BOUNDING_BOX_Y 10.0f
#define BRICK_INITIAL_WIDTH 64.0f
#define BRICK_INITIAL_HEIGHT 32.0f
#define BRICK_BOUNDING_BOX_X 64.0f
#define BRICK_BOUNDING_BOX_Y 32.0f
#define COLLIDER_INITIAL_MASS 10.0f
#define COLLIDER_INITIAL_ELASTIC 1.0f
#define COLLIDER_INITIAL_POSITION_X 100.0f
#define COLLIDER_INITIAL_POSITION_Y 100.0f
#define COLLIDER_INITIAL_VELOCITY_X 0.0f
#define COLLIDER_INITIAL_VELOCITY_Y 0.0f
#define COLLIDER_INITIAL_ACCELERATION_X 0.0f
#define COLLIDER_INITIAL_ACCELERATION_Y 0.0f
#define BOUNDING_BOX_INITIAL_X 64.0f
#define BOUNDING_BOX_INITIAL_Y 32.0f
#define BOUNDARY_INITIAL_WIDTH 1280
#define BOUNDARY_INITIAL_HEIGHT 720
#define WALL_INITIAL_WIDTH 1290.0f
#define WALL_INITIAL_HEIGHT 5.0f
#define WALL_BOUNDING_BOX_X 1290.0f
#define WALL_BOUNDING_BOX_Y 5.0f
#define NORMAL_INITIAL_X 0.0f
#define NORMAL_INITIAL_Y -1.0f
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define PADDLE_INITIAL_POS_X 640.0f
#define PADDLE_INITIAL_POS_Y 680.0f
#define PADDLE_INITIAL_SIZE_X 104.0f
#define PADDLE_INITIAL_SIZE_Y 24.0f
#define PADDLE_VELOCITY_FACTOR 20.0f
#define PADDLE_BOUNDING_BOX_X 104.0f
#define PADDLE_BOUNDING_BOX_Y 24.0f
#define BRICK_LEVEL_ONE_NUM 48
#define BRICK_LEVEL_TWO_NUM 48
#define BRICK_LEVEL_THREE_NUM 48
#define QUIT true
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define LIFE_TEXTURE_POSITION_X 100.0f
#define LIFE_TEXTURE_POSITION_Y 30.0f
#define SCORE_TEXTURE_POSITION_X 1000.0f
#define SCORE_TEXTURE_POSITION_Y 30.0f
#define LEVEL_TEXTURE_POSITION_X 500.0f
#define LEVEL_TEXTURE_POSITION_Y 30.0f
#define LOSE_TEXTURE_POSITION_X 640.0f
#define LOSE_TEXTURE_POSITION_Y 360.0f
#define WIN_TEXTURE_POSITION_X 640.0f
#define WIN_TEXTURE_POSITION_Y 360.0f
#define WALL_TOP_INITIAL_POS_X 640.0f
#define WALL_TOP_INITIAL_POS_Y -5.0f
#define WALL_TOP_INITIAL_WIDTH 1300.0f
#define WALL_TOP_INITIAL_HEIGHT 10.0f
#define WALL_TOP_NORMAL_X 0.0f
#define WALL_TOP_NORMAL_Y 1.0f
#define WALL_LEFT_INITIAL_POS_X -5.0f
#define WALL_LEFT_INITIAL_POS_Y 360.0f
#define WALL_LEFT_INITIAL_WIDTH 10.0f
#define WALL_LEFT_INITIAL_HEIGHT 1300.0f
#define WALL_LEFT_NORMAL_X 1.0f
#define WALL_LEFT_NORMAL_Y 0.0f
#define WALL_RIGHT_INITIAL_POS_X 1285.0f
#define WALL_RIGHT_INITIAL_POS_Y 360.0f
#define WALL_RIGHT_INITIAL_WIDTH 10.0f
#define WALL_RIGHT_INITIAL_HEIGHT 1300.0f
#define WALL_RIGHT_NORMAL_X -1.0f
#define WALL_RIGHT_NORMAL_Y 0.0f
#define BALL_MASS 5.0f
#define WALL_MASS 30.0f
#define PADDLE_MASS 10.0f
#define BRICK_MASS 15.0F
#define PADDLE_ELASTIC 0.5f
#define MAIN_MENU_TEXTURE_POSITION_X 640.0f
#define MAIN_MENU_TEXTURE_POSITION_Y 100.0f
#define START_TEXT_TEXTURE_POSITION_X 640.f
#define START_TEXT_TEXTURE_POSITION_Y 180.0f
#define MAIN_MENU_START_BUTTON_POSITION_X 540.0f
#define MAIN_MENU_START_BUTTON_POSITION_Y 155.0f
#define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_X 640.0f
#define LANGUAGE_SETTING_TEXT_TEXTURE_POSITION_Y 260.0f
#define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_X 540.0f
#define MAIN_MENU_LANGUAGE_SETTING_BUTTON_POSITION_Y 235.0f
#define QUIT_TEXT_TEXTURE_POSITION_X 640.0f
#define QUIT_TEXT_TEXTURE_POSITION_Y 340.0f
#define PAUSE_TEXT_TEXTURE_POSITION_X 640.0f
#define PAUSE_TEXT_TEXTURE_POSITION_Y 420.0f
#define RETURN_TEXT_TEXTURE_POSITION_X 640.0f
#define RETURN_TEXT_TEXTURE_POSITION_Y 500.0f
#define PAUSE_MENU_TEXTURE_POSITION_X 640.0f
#define PAUSE_MENU_TEXTURE_POSITION_Y 300.0f
#define RESUME_TEXT_TEXTURE_POSITION_X 640.0f
#define RESUME_TEXT_TEXTURE_POSITION_Y 380.0f
#define SETTING_MENU_TEXTURE_POSITION_X 640.0f
#define SETTING_MENU_TEXTURE_POSITION_Y 100.0f
#define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
#define FIRST_LANGUAGE_TEXT_TEXTURE_POSITION_Y 180.0f
#define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_X 540.0f
#define SETTING_MENU_FIRST_LANGUAGE_BUTTON_POSITION_Y 155.0f
#define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_X 640.0f
#define SECOND_LANGUAGE_TEXT_TEXTURE_POSITION_Y 260.0f
#define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_X 540.0f
#define SETTING_MENU_SECOND_LANGUAGE_BUTTON_POSITION_Y 235.0f
#define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_X 640.0f
#define SETTING_MENU_RETURN_BUTTON_TEXT_TEXTURE_POSITION_Y 340.0f
#define RETURN_BUTTON_POSITION_X 540.0f
#define RETURN_BUTTON_POSITION_Y 310.0f




#define BUTTON_WIDTH 190.0f
#define BUTTON_HEIGHT 49.0f
#define BUTTON_SIZE_X 190.0f
#define BUTTON_SIZE_Y 49.0f












#endif /* Constants_h */
